channels:
  - conda-forge
  - defaults
dependencies:
  - flake8
  - numpy >= 1.11
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  - librosa >= 0.8.0
  - pip
  - pip:
    - kaldi-io
    - scipy
    - parameterized
