channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - apipkg=1.5
  - appdirs=1.4.3
  - attrs=20.2.0
  - audioread=2.1.8
  - blas=1.0=mkl
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates
  - certifi
  - cffi=1.14.3
  - chardet=3.0.4
  - codecov=2.1.9
  - conda=4.8.5
  - conda-package-handling=1.6.1
  - coverage=5.3
  - cryptography=3.1
  - cycler=0.10.0
  - decorator=4.4.2
  - execnet=1.7.1
  - ffmpeg=4.3
  - flake8=3.8.3
  - freetype=2.10.2
  - gettext=0.19.8.1
  - gmp=6.2.0
  - gnutls=3.6.13
  - idna=2.10
  - importlib-metadata=1.7.0
  - iniconfig=1.0.1
  - intel-openmp=2019.4
  - joblib=0.16.0
  - jpeg=9d
  - kiwisolver=1.2.0
  - lame=3.100
  - lcms2=2.11
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libflac=1.3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libllvm9=9.0.1
  - libogg=1.3.2
  - libpng=1.6.37
  - librosa=0.8.0
  - libsndfile=1.0.28
  - libtiff=4.1.0
  - libuv=1.39.0
  - libvorbis=1.3.7
  - libwebp-base=1.1.0
  - llvm-openmp=10.0.1
  - llvmlite=0.33.0
  - lz4-c=1.9.2
  - matplotlib-base=3.3.0
  - mccabe=0.6.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - more-itertools=8.5.0
  - ncurses=6.2
  - nettle=3.4.1
  - ninja=1.10.1
  - numba=0.50.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1h
  - packaging=20.4
  - pillow=7.2.0
  - pip=20.2.3
  - pluggy=0.13.1
  - pooch=1.2.0
  - py=1.9.0
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pyflakes=2.2.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pysoundfile=0.10.2
  - pytest=6.0.2
  - pytest-cov=2.10.1
  - pytest-forked=1.2.0
  - pytest-xdist=2.1.0
  - python=3.8.3
  - python-dateutil=2.8.1
  - python.app=2
  - python_abi=3.8
  - readline=8.0
  - requests=2.24.0
  - resampy=0.2.2
  - ruamel_yaml=0.15.87
  - scikit-learn=0.23.2
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - tqdm=4.49.0
  - typing_extensions=3.7.4.3
  - urllib3=1.25.10
  - wheel=0.35.1
  - x264=1!152.20180806
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - dataclasses==0.7
    - kaldi-io==0.9.4
    - parameterized==0.7.4
    - scipy==1.5.2
